version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile.stage
    container_name: api
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=prod
      - PORT=5050
      - FRONT_URL=https://464industries.com
      - DB_HOST=db
      - DB_USER=api-user
      - DB_PASSWORD=api-user-password
      - DB_DATABASE=challenges
      - MJ_APIKEY=3d951e6aa8529c1eab3b76426873edf1
      - MJ_APISECRET=4e45906c83730b15eca96f117d708fd1
      - MJ_EMAIL_FROM=hadjar.habib.dev@gmail.com
      - MJ_EMAIL_NAME=habib
    networks:
      - api-network
    restart: always
    labels:
      api_logging: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
    
  dbms:
    image: mariadb
    restart: always
    ports:
      - "3309:3306"
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_ROOT_PASSWORD=Hv4ffyMpbW8tjJby
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
    ]
    volumes:
      - ./db/dbms-data:/var/lib/mysql
      - ./db/mariadb.cnf:/etc/mysql/mariadb.cnf
    networks:
      - api-network

  proxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/api-https-final.nginx.conf:/etc/nginx/conf.d/api.nginx.conf
      - ./nginx/certbot/www:/var/www/certbot/:ro
      - ./nginx/certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - api-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www/:/var/www/certbot/:rw
      - ./nginx/certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
    name: api-network